"""Import kept Poly Haven CC0 FBX props into /Game/Props (Band 5 §8/§18).

Run: UnrealEditor-Cmd.exe <uproject> -run=pythonscript -script="<this>"

Backlog #24 (CC0-Prop-Pass): the slice props were still Cube/Cylinder
blockout proxies. JOBS maps the kept source files (D:\\Assets\\CC0\\Models,
downloaded + MD5-verified against the Poly Haven files API 2026-09-25,
license CC0 verified on polyhaven.com/license, rows in
ASSET-LICENSES.csv) to SM_* static meshes:

    katana_stand_01/katana_stand_01_1k.fbx             -> SM_BladeRack_Klingenhof
    Barrel_01/Barrel_01_1k.fbx                         -> SM_Barrel_Brunnfeld
    painted_wooden_bench/painted_wooden_bench_1k.fbx   -> SM_Bench_Brunnfeld

Import settings: mesh ONLY - no materials, no textures (Band 5 §9 /
backlog #24: props are dressed with the existing MI_* instances in
dress_arena.py, "kein Material-Neubau"). Every optional 5.8 import
property is set through a dual-name probe that logs acceptance.
Idempotent: replace_existing re-imports, so a bad first import
self-heals.

Collision (probed dead ends 2026-09-25, all in commandlets):
  * FBX auto_generate_collision is accepted but only ever yields an
    in-memory convex hull - and a convex hull never becomes a queryable
    body in a non-ticking process (fresh-process capsule sweep MISS,
    component line trace MISS, get_closest_point_on_collision -> -1,
    while a freshly spawned engine Cube BOX hits in the same process)
  * UStaticMesh.collision_trace_flag write is NOT exposed in 5.8 python;
    the BodySetup flag persists on disk but is not the authoritative one
  * EditorStaticMeshLibrary.add_simple_collisions silently returns -1;
    StaticMeshEditorSubsystem is not registered in commandlets (None)
  * FKAggregateGeom/FKBoxElem struct classes are not exposed to python
Winning route: UBX_ box collision baked into the FBX by
ArtSource/Props/add_ubx_collision.py -> the importer writes a real
FKBoxElem (box>=1 in AggGeom) and Box primitives build their body
synchronously in any process. ensure_collision below only READS state now
(plus keeps the flag write as supplementary evidence); the proof is the
capsule sweep on a temp actor at z=50000:

    S=... simple AggGeom probe, C=... render-mesh probe

Evidence per mesh: world bounds extent (cm scale sanity), material slot
count, body_setup/AggGeom state, sweep result. Writes
<Project>/Saved/MeshImportResult.txt, prints RESULT: ok=<bool>.
"""
import os
import traceback

# (source file relative to SRC_ROOT, SM_ asset name)
# Sources are the *_ubx.fbx derivatives: original Poly Haven FBX + a
# UBX_<name>_00 box collision object generated by
# ArtSource/Props/add_ubx_collision.py (Blender 5.2.1 headless) - see the
# Collision section of this docstring.
JOBS = [
    ("katana_stand_01/katana_stand_01_1k_ubx.fbx", "SM_BladeRack_Klingenhof"),
    ("Barrel_01/Barrel_01_1k_ubx.fbx", "SM_Barrel_Brunnfeld"),
    ("painted_wooden_bench/painted_wooden_bench_1k_ubx.fbx", "SM_Bench_Brunnfeld"),
]

SRC_ROOT = "D:/Assets/CC0/Models"
DEST_PATH = "/Game/Props"

# Temp-actor probe height: far above any level geometry.
PROBE_Z = 50000.0

_INTROSPECTED = False

lines = []


def log(msg):
    lines.append(msg)
    print("[MESH] " + msg)


def set_any(obj, names, value):
    """Try several property spellings; log what 5.8 actually accepts."""
    last = None
    for name in names:
        try:
            obj.set_editor_property(name, value)
            got = obj.get_editor_property(name)
            log("option %s -> %s (read-back %s)" % (name, value, got))
            return True
        except Exception as exc:
            last = exc
    log("option %s not accepted: %s" % (names, last))
    return False


def agg_counts(mesh):
    """(box, convex) element counts, -1 when unreadable."""
    import unreal
    out = (-1, -1)
    try:
        bs = mesh.get_editor_property("body_setup")
        if bs is None:
            return out
        agg = bs.get_editor_property("agg_geom")
        try:
            boxes = agg.get_editor_property("box_elems")
            nbox = len(boxes) if boxes is not None else -1
        except Exception:
            nbox = -1
        try:
            conv = agg.get_editor_property("convex_elems")
            nconv = len(conv) if conv is not None else -1
        except Exception:
            nconv = -1
        out = (nbox, nconv)
    except Exception as exc:
        log("agg probe failed: %s" % exc)
    return out


def find_class(*candidates):
    import unreal
    for n in candidates:
        if hasattr(unreal, n):
            return getattr(unreal, n), n
    return None, None


def ensure_collision(mesh, asset_path, name, extent=None, local_center=None):
    """Fill collision data / flag, log every step, return dict of state."""
    import unreal
    state = {}
    try:
        bs = mesh.get_editor_property("body_setup")
        state["body_setup"] = "yes" if bs else "NONE"
    except Exception as exc:
        bs = None
        state["body_setup"] = "read-failed: %s" % exc

    # Attack 1: keep the flag at CTF_USE_DEFAULT so the body uses the
    # AggGeom primitives (the UBX box). The earlier attempt to force
    # CTF_USE_COMPLEX_AS_SIMPLE was actively HARMFUL: it makes body
    # creation cook the render mesh triangle soup, that cook is async and
    # never lands in a non-ticking commandlet, and the perfectly good box
    # element goes unused - evidence: fresh-process sweeps stayed MISS
    # with flag=3 while the engine cube (flag DEFAULT + box) always hit.
    flag = None
    for vname in ("CTF_USE_DEFAULT", "CTC_USE_DEFAULT"):
        if hasattr(unreal.CollisionTraceFlag, vname):
            flag = getattr(unreal.CollisionTraceFlag, vname)
            break
    state["flag_enum"] = str(flag)
    if flag is not None and bs is not None:
        state["bs_flag_set"] = set_any(bs, ["collision_trace_flag"], flag)
        if state["bs_flag_set"]:
            try:
                state["saved"] = unreal.EditorAssetLibrary.save_asset(asset_path)
            except Exception as exc:
                state["saved"] = "failed: %s" % exc
    else:
        state["bs_flag_set"] = "no-candidate"

    # Attack 1b: strip leftover convex hulls (from the very first import's
    # auto_generate_collision). A convex element must be COOKED, that cook
    # is async, and the pending cook blocks the WHOLE body init - taking
    # the cook-free box element down with it. Evidence: fresh processes
    # showed box=1 + flag=DEFAULT and still closest=-1 / sweep MISS,
    # while the engine cube (box only) always hit. Result: AggGeom
    # box-only = deterministic synchronous body.
    if bs is not None:
        try:
            agg = bs.get_editor_property("agg_geom")
            nconv = len(agg.get_editor_property("convex_elems") or [])
            if nconv > 0:
                agg.set_editor_property("convex_elems", [])
                bs.set_editor_property("agg_geom", agg)
                state["convex_stripped"] = nconv
                state["strip_saved"] = unreal.EditorAssetLibrary.save_asset(
                    asset_path)
            else:
                state["convex_stripped"] = 0
        except Exception as exc:
            state["convex_stripped"] = "failed: %s" % exc

    # Attack 2: write a real FKBoxElem into AggGeom directly. Flag-agnostic:
    # with a primitive on disk, CTF_USE_DEFAULT resolves to simple collision
    # in ANY fresh process. (auto_generate_collision only ever produced an
    # in-memory convex=1; the library/subsystem helpers either need an
    # editor-subsystem instance that commandlets do not register, or
    # silently return False/-1 - all probed.)
    box, conv = agg_counts(mesh)
    state["agg_before"] = "box=%d convex=%d" % (box, conv)
    if box < 1 and extent is not None:
        agg_cls, agg_name = find_class("FKAggregateGeom", "AggregateGeom")
        elem_cls, elem_name = find_class("FKBoxElem", "BoxElem", "FBoxElem")
        state["structs"] = "agg=%s elem=%s" % (agg_name, elem_name)
        if agg_cls is None or elem_cls is None:
            state["direct"] = "struct classes not exposed"
            log("unreal agg/elem candidates: %s" % [
                n for n in dir(unreal)
                if ("agg" in n.lower() or "box" in n.lower()
                    or "elem" in n.lower())][:60])
        else:
            try:
                agg = bs.get_editor_property("agg_geom")
                elem = elem_cls()
                center = local_center or (0.0, 0.0, 0.0)
                for pn, val in (("center", unreal.Vector(*center)),
                                ("x", float(extent[0])),
                                ("y", float(extent[1])),
                                ("z", float(extent[2]))):
                    if not set_any(elem, [pn], val):
                        state["direct"] = "elem field failed: " + pn
                        break
                else:
                    agg.set_editor_property("box_elems", [elem])
                    set_any(bs, ["agg_geom"], agg)
                    box2, conv2 = agg_counts(mesh)
                    state["direct"] = "box written agg box=%d convex=%d" % (
                        box2, conv2)
                    if box2 >= 1:
                        state["saved"] = unreal.EditorAssetLibrary.save_asset(
                            asset_path)
            except Exception as exc:
                state["direct"] = "failed: %s" % exc

    # Attack 3 (kept for evidence): editor helper chain.
    if agg_counts(mesh)[0] < 1:
        ss = None
        if hasattr(unreal, "StaticMeshEditorSubsystem"):
            try:
                ss = unreal.get_editor_subsystem(
                    unreal.StaticMeshEditorSubsystem)
            except Exception as exc:
                log("StaticMeshEditorSubsystem get raised: %s" % exc)
        log("StaticMeshEditorSubsystem instance: %r" % (ss,))
        attempts = []
        if ss is not None:
            attempts.append(("subsystem+BOX",
                             lambda: ss.add_simple_collisions(
                                 mesh, unreal.ScriptingCollisionShapeType.BOX)))
        lib = unreal.EditorStaticMeshLibrary
        attempts.append(("lib+BOX",
                         lambda: lib.add_simple_collisions(
                             mesh, unreal.ScriptingCollisionShapeType.BOX)))
        for label, fn_call in attempts:
            try:
                ret = fn_call()
                log("helper %s ret=%s agg=%s" % (label, ret, agg_counts(mesh)))
            except Exception as exc:
                log("helper %s failed: %s" % (label, exc))

    box, conv = agg_counts(mesh)
    state["agg"] = "box=%d convex=%d" % (box, conv)
    try:
        state["complexity"] = str(
            unreal.EditorStaticMeshLibrary.get_collision_complexity(mesh))
    except Exception as exc:
        state["complexity"] = "probe-failed: %s" % exc
    for cooked_name in ("has_cooked_collision_data", "b_has_cooked_collision_data"):
        try:
            state["cooked"] = str(bs.get_editor_property(cooked_name))
            break
        except Exception:
            state["cooked"] = "prop-not-exposed"
    return state


def probe_flow(subsys, sm_cls, mesh, asset_path, name):
    """Temp actor at PROBE_Z: bounds, collision ensure, recreate, sweeps."""
    import unreal
    global _INTROSPECTED
    actor = None
    try:
        actor = subsys.spawn_actor_from_class(
            sm_cls, unreal.Vector(0.0, 0.0, PROBE_Z),
            unreal.Rotator(0.0, 0.0, 0.0))
        actor.set_actor_label("__tmp_meshprobe")
        comp = actor.get_component_by_class(unreal.StaticMeshComponent)
        comp.set_static_mesh(mesh)
        if not _INTROSPECTED:
            _INTROSPECTED = True
            introspect(unreal, mesh=mesh, comp=comp)
        origin, extent = actor.get_actor_bounds(False, False)
        log("%s extent=(%.1f, %.1f, %.1f) cm slots=%d" % (
            name, extent.x, extent.y, extent.z, comp.get_num_materials()))
        local_center = (origin.x, origin.y, origin.z - PROBE_Z)

        state = ensure_collision(mesh, asset_path, name,
                                 extent=(extent.x, extent.y, extent.z),
                                 local_center=local_center)
        log("%s collision state: %s" % (name, state))

        # Recreate the component body from the now-patched asset, then sweep.
        comp.set_static_mesh(None)
        comp.set_static_mesh(mesh)
        start = unreal.Vector(origin.x, origin.y, origin.z + extent.z + 100.0)
        end = unreal.Vector(origin.x, origin.y, origin.z - extent.z + 40.0)
        for tag, complex_trace in (("S", False), ("C", True)):
            res = unreal.SystemLibrary.capsule_trace_single(
                actor.get_world(), start, end, 20.0, 30.0,
                unreal.TraceTypeQuery.TRACE_TYPE_QUERY1,
                complex_trace, [], unreal.DrawDebugTrace.NONE)
            log("%s sweep %s=%s(%s)" % (
                name, tag, "HIT" if res is not None else "MISS",
                "None" if res is None else repr(res)[:70]))
    except Exception:
        log("PROBE-FAIL %s\n%s" % (name, traceback.format_exc()))
    finally:
        if actor is not None:
            try:
                subsys.destroy_actor(actor)
            except Exception as exc:
                log("probe cleanup failed: %s" % exc)


def filtered_dir(obj):
    keys = ("coll", "trace", "flag", "complex", "body", "cook")
    try:
        return [x for x in dir(obj)
                if any(k in x.lower() for k in keys)
                and not x.startswith("__")]
    except Exception as exc:
        return "dir-failed: %s" % exc


def introspect(unreal, mesh=None, comp=None):
    """Where does the authoritative CollisionTraceFlag live? One-time log."""
    log("dir(StaticMesh) coll-keys: %s" % filtered_dir(unreal.StaticMesh))
    log("dir(StaticMeshEditorSubsystem): %s" % (
        filtered_dir(unreal.StaticMeshEditorSubsystem)
        if hasattr(unreal, "StaticMeshEditorSubsystem") else "not exposed"))
    if mesh is not None:
        log("dir(mesh) coll-keys: %s" % filtered_dir(mesh))
        try:
            bs = mesh.get_editor_property("body_setup")
            log("dir(body_setup) coll-keys: %s" % filtered_dir(bs))
        except Exception as exc:
            log("dir(body_setup) failed: %s" % exc)
    if comp is not None:
        log("dir(comp) coll-keys: %s" % filtered_dir(comp))
        try:
            bi = comp.get_editor_property("body_instance")
            log("dir(body_instance) coll-keys: %s" % filtered_dir(bi))
        except Exception as exc:
            log("dir(body_instance) failed: %s" % exc)


def disable_interchange_fbx(subsys, sm_cls):
    """UE 5.8 routes FBX through Interchange, which silently DROPS UBX_/UCX_
    collision nodes (probed 2026-09-25: box stayed 0 with the collision as
    sibling AND as child of the render mesh; the node never even appears in
    the import log). Epic forum workaround: turn the Interchange FBX
    pipeline off -> the legacy FBX importer handles UBX_ naming rules.
    Session-only CVar (no ini change), executed before the import loop."""
    import unreal
    probe = None
    try:
        probe = subsys.spawn_actor_from_class(
            sm_cls, unreal.Vector(0.0, 0.0, 100000.0),
            unreal.Rotator(0.0, 0.0, 0.0))
        res = unreal.SystemLibrary.execute_console_command(
            probe.get_world(), "Interchange.FeatureFlags.Import.FBX 0")
        log("cvar Interchange.FeatureFlags.Import.FBX 0 -> ret=%s" % (res,))
    except Exception as exc:
        log("cvar disable failed: %s" % exc)
    finally:
        if probe is not None:
            try:
                subsys.destroy_actor(probe)
            except Exception:
                pass


def main():
    import unreal

    result_path = unreal.Paths.project_saved_dir() + "MeshImportResult.txt"
    success = False
    try:
        tools = unreal.AssetToolsHelpers.get_asset_tools()
        subsys = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
        sm_cls = unreal.load_class(None, "/Script/Engine.StaticMeshActor")
        if sm_cls is None:
            raise RuntimeError("StaticMeshActor class missing")

        # Attack 0: legacy FBX importer (UBX naming rules), see helper.
        disable_interchange_fbx(subsys, sm_cls)

        imported = []
        for rel, name in JOBS:
            src = SRC_ROOT + "/" + rel
            if not os.path.isfile(src):
                log("SOURCE MISSING: " + src)
                continue

            task = unreal.AssetImportTask()
            task.filename = src
            task.destination_path = DEST_PATH
            task.destination_name = name
            set_any(task, ["automated"], True)
            set_any(task, ["replace_existing"], True)
            set_any(task, ["save"], True)

            opts = unreal.FbxImportUI()
            set_any(opts, ["import_mesh", "bImportMesh"], True)
            set_any(opts, ["import_as_skeletal", "bImportAsSkeletal"], False)
            # Band 5 §9 / backlog #24: MI_* only, no imported materials.
            set_any(opts, ["import_materials", "bImportMaterials"], False)
            set_any(opts, ["import_textures", "bImportTextures"], False)
            set_any(opts, ["import_animations", "bImportAnimations"], False)
            try:
                smd = opts.get_editor_property("static_mesh_import_data")
                if smd is None:
                    log("static_mesh_import_data is None on fresh FbxImportUI")
                else:
                    set_any(smd, ["combine_meshes", "bCombineMeshes"], True)
                    set_any(smd, ["generate_lightmap_uvs", "bGenerateLightmapUVs"],
                            True)
                    # Custom UBX collision rides in the FBX; auto-generate
                    # would only mask a failed UBX detection with the
                    # useless convex hull (proven non-blocking).
                    set_any(smd, ["auto_generate_collision", "bAutoGenerateCollision"],
                            False)
            except Exception as exc:
                log("static_mesh_import_data unavailable: %s" % exc)
            task.options = opts

            try:
                tools.import_asset_tasks([task])
            except Exception:
                log("IMPORT-THROW %s\n%s" % (name, traceback.format_exc()))
                continue

            asset_path = "%s/%s" % (DEST_PATH, name)
            if not unreal.EditorAssetLibrary.does_asset_exist(asset_path):
                try:
                    paths = task.get_editor_property("imported_object_paths")
                except Exception:
                    paths = "?"
                log("IMPORT-MISSING %s imported=%s" % (asset_path, paths))
                continue
            imported.append(asset_path)
            log("imported %s" % asset_path)

            mesh = unreal.EditorAssetLibrary.load_asset(asset_path)
            if mesh is None:
                log("LOAD-FAIL " + asset_path)
                continue

            probe_flow(subsys, sm_cls, mesh, asset_path, name)

        # One-time API-surface evidence for the vault.
        helpers = [x for x in dir(unreal.EditorStaticMeshLibrary)
                   if "coll" in x.lower() or "convex" in x.lower()]
        log("EditorStaticMeshLibrary collision helpers: %s" % helpers)

        success = len(imported) == len(JOBS)
        log("imported=%d/%d" % (len(imported), len(JOBS)))

    except Exception:
        log("TOP-FAIL\n" + traceback.format_exc())

    with open(result_path, "w") as f:
        f.write("success=%s\n" % success)
        f.write("\n".join(lines) + "\n")
    print("[MESH] done success=%s" % success)
    print("RESULT: ok=%s" % success)
    return success


if __name__ == "__main__":
    main()
